baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Application Modernization Cookbook"
copyright = "@2020, Pivotal VMware Software, Inc. All Rights Reserved, Confidential"
theme = "hugo-theme-docdock"
publishDir = "public"
pygmentsCodeFences = true
pygmentsStyle = "friendly"
enableRobotsTXT = true
enableGitInfo = true

[params]
themeStyle = "original"
disableHomeIcon = true
description = "Application Modernization Cookbook"
noCategoryLink = true
showVisitedLinks = false
noSearch = false
noHomeIcon = true
ordersectionsby = "title"
ignoreFiles = [ "\\.adoc$" ]
disableNavChevron = true
menushortcutsnewtab = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h5>&nbsp;</h5>"
name = "<i class='fa fa-tag'></i>&nbsp;&nbsp;All Tags"
url = "/tags/"
